# Generated by Django 4.1.2 on 2022-10-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_finch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='stuffs',
            field=models.ManyToManyField(to='main_app.stuffwithfinch'),
        ),
    ]
