# Generated by Django 4.1.2 on 2022-10-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='stuffs',
            field=models.ManyToManyField(to='main_app.stuff'),
        ),
    ]
